### ISSUE TITLE
octynectl 1.0 tracker

### ISSUE THREAD

**Issue by retrixe** [retrixe/octynectl#4]
- [x] ~~Shrink binary size (search "rust strip debug info", remove useless libraries)~~
- [x] Improve error handling (reduce `exit` and `unwrap` calls)
- [x] ~~Interactive console (use `\r` for bottom prompt, I guess?)~~ Postponed to future version
- [x] Implement `console-v2` protocol for more robustness
- [x] Support WebSocket commands under Windows platform
